<map name="main" id="main" onmousemove="cI()"><area onclick="return po(2241);" href="http://mycom.com"coords="410,110,640,340" title="This my ADS" data="My Company" alt="This my ADS">
<area onclick="return po(9268);" href="http://testcompany.com"coords="680,460,830,610" title="This is Best Company in the word" data="Test Company" alt="This is Best Company in the word">
<area onclick="return po(8223);" href="http://headerimg.com"coords="230,410,430,460" title="Amazing Header Image" data="Your Header Image" alt="Amazing Header Image">
<area onclick="return po(0);" href="http://liverpool.com"coords="0,0,230,230" title="We flush what needs to be flushed down" data="Liverpool Kutay Incorporated" alt="We flush what needs to be flushed down">
<area onclick="return po(1269);" href="http://www.theservicenetwork.co"coords="690,60,1220,180" title="We are Utopia" data="Utopia" alt="We are Utopia">
<area onclick="return po(63);" href="http://dev.vskytech.com/p22_milliondolar"coords="630,0,690,90" title="tesst" data="test" alt="tesst">
<area onclick="return po(3869);" href="http://fb.com/izegbu"coords="690,190,990,390" title="Edozie Izegbu" data="" alt="Edozie Izegbu">
<area onclick="return po(5515);" href="http://anc.com"coords="1150,270,1200,370" title="quanvan" data="hoa" alt="quanvan">
</map>